on: [push]

name: 'Package: Debian GNU + Linux (x86_64)'

jobs:
  deb_x86-64:
    name: Debian GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Install 'cargo-deb'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb
      - name: Build & package larz
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: --separate-debug-symbols -- --all-features --target x86_64-unknown-linux-gnu
      - name: Upload larz build artifact to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-larz.deb.gnu+linux
          path: ./target/debian/larz_*_amd64.deb
          if-no-files-found: error