on:
  push:
    branches:    
      - 'master'

name: 'Build: macOS (Universal)'

jobs:
  mac_universal:
    name: macOS (Universal)
    runs-on: macos-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Install development dependencies
        run: |
          brew update > /dev/null
      - name: Setup Rust toolchain for AMD64
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          default: true
          profile: minimal
      - name: Setup Rust toolchain for ARM64
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-apple-darwin
          default: false
          profile: minimal
      - name: Build larz for AMD64
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --release --target x86_64-apple-darwin --all-features
      - name: Build larz for AARCH64
        run: |
          SDKROOT=$(xcrun -sdk macosx --show-sdk-path) \
          MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version) \
          cargo build --release --target=aarch64-apple-darwin --all-features
      - name: Prepare larz for upload
        run: |
          lipo -create \
          -output target/larz \
          target/aarch64-apple-darwin/release/larz \
          target/x86_64-apple-darwin/release/larz
          lipo -create \
          -output target/liblarz.dylib \
          target/aarch64-apple-darwin/release/liblarz.dylib \
          target/x86_64-apple-darwin/release/liblarz.dylib
          lipo -create \
          -output target/liblarz.a \
          target/aarch64-apple-darwin/release/liblarz.a \
          target/x86_64-apple-darwin/release/liblarz.a
          cd ./target
          tar -cvf universal-larz.osx.tar \
          larz \
          liblarz.dylib \
          liblarz.a

          cd ./x86_64-apple-darwin/release/
          tar -cvf x86_64-larz.osx.tar \
          larz \
          liblarz.dylib \
          liblarz.a

          cd ../../aarch64-apple-darwin/release/
          strip ./larz
          chmod +x ./larz
          tar -cvf aarch64-larz.osx.tar \
          larz \
          liblarz.dylib \
          liblarz.a
      - name: Upload larz AMD64 build artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-larz.osx
          path: ./target/x86_64-apple-darwin/release/x86_64-larz.osx.tar
          if-no-files-found: error
      - name: Upload larz ARM64 build artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-larz.osx
          path: ./target/aarch64-apple-darwin/release/aarch64-larz.osx.tar
          if-no-files-found: error
      - name: Upload larz Universal build artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: universal-larz.osx
          path: ./target/universal-larz.osx.tar
          if-no-files-found: error