on: [push]

name: 'Build: macOS (x86_64)'

jobs:
  mac_x86-64:
    name: macOS (x86_64)
    runs-on: macos-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          default: true
          profile: minimal
      - name: Build larz
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-apple-darwin
      - name: Prepare larz for upload
        run: |
          cd ./target/x86_64-apple-darwin/release/
          strip ./larz
          chmod +x ./larz
          tar -cvf x86_64-larz.osx.tar \
          larz \
          liblarz.dylib \
          liblarz.a
      - name: Upload larz build artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-larz.osx
          path: ./target/x86_64-apple-darwin/release/x86_64-larz.osx.tar
          if-no-files-found: error